### ISSUE TITLE
Release packaging of javaagent needs to include asm file

### ISSUE THREAD

**Issue by tobespc** [RuntimeTools/javametrics#46]
The current zip that is on the release tab for the agent does not contain the asm directory and files.  As such, the javaagent will not run.  The zip needs to be updated to include the asm files

**Comment by ind1go** [comment]
Any chance this is going to be fixed? At the moment this means the whole package doesn't work.

**Comment by robbinspg** [comment]
@ind1go apologies for the delay. There is now a 1.0.1 release zip containing all the necessary jars. I will update the deployment instructions in due course.

**Comment by ind1go** [comment]
Thank you!

**Comment by robbinspg** [comment]
PR https://github.com/RuntimeTools/javametrics/pull/63 creates the release zip for future releases.

Closing this.
