### ISSUE TITLE
javametrics-dash-1.1.0-SNAPSHOT.war does not contain graphmetrics

### ISSUE THREAD

**Issue by fmhwong** [RuntimeTools/javametrics#66]
git clone git@github.com:RuntimeTools/javametrics.git
cd javametrics
mvn install

The build was successful but `javametrics-dash-1.1.0-SNAPSHOT.war` does not contain /graphmetrics folder

**Comment by mattcolegate** [comment]
@fmhwong you missed the --recursive option off the git clone

**Comment by fmhwong** [comment]
Ah, I see, thx
